### ISSUE TITLE
Precommit hooks

### ISSUE THREAD

**Issue by shantanuraj** [heytherewill/toggl-cli#17]
- Configure precommit hook to ensure
- App builds
- No lint warnings (`clippy --fix` to autofix common issues)

**Comment by shantanuraj** [comment]
@heytherewill do we still need this now that we have CI?

I was looking for pure Rust solution cause I'd like to keep that 100% Rust language stat :D 

and this is the solution that the [rust-analyzer/rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) repo uses https://github.com/rust-analyzer/rust-analyzer/pull/271 based on this spec [matklad/cargo-xtask](https://github.com/matklad/cargo-xtask)

**Comment by heytherewill** [comment]
No longer needed, because CI
